compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - code: YN0002
    level: discard

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  os:
    - current
    - linux
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-4.1.1.cjs
